-- Migration: 0002_rebuild_schema
-- Drops the 0001 tables and replaces them with four new tables:
--   country   — lookup table of countries
--   company   — a company, tied to a country (FK)
--   employer  — a hiring entity / division inside a company (FK → company)
--   people    — a person, optionally linked to their current employer (FK → employer)
-- All tables carry created_at, updated_at, deleted_at for soft-delete support.
-- Seed data is inserted at the bottom.

-- ── Drop old tables in FK-safe order ────────────────────────────────────────
DROP TABLE IF EXISTS role           CASCADE;
DROP TABLE IF EXISTS activity_event CASCADE;
DROP TABLE IF EXISTS person         CASCADE;
DROP TABLE IF EXISTS employer       CASCADE;

-- ── New tables ───────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS country (
    id         uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
    name       text        NOT NULL,
    code       text        NOT NULL,   -- ISO 3166-1 alpha-2, e.g. 'US', 'UA'
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    deleted_at timestamptz
);

CREATE TABLE IF NOT EXISTS company (
    id         uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
    name       text        NOT NULL,
    industry   text,
    country_id uuid        NOT NULL REFERENCES country(id) ON DELETE RESTRICT,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    deleted_at timestamptz
);

CREATE TABLE IF NOT EXISTS employer (
    id         uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
    name       text        NOT NULL,
    company_id uuid        NOT NULL REFERENCES company(id) ON DELETE RESTRICT,
    location   text,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    deleted_at timestamptz
);

CREATE TABLE IF NOT EXISTS people (
    id          uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
    name        text        NOT NULL,
    email       text,
    employer_id uuid        REFERENCES employer(id) ON DELETE SET NULL,
    location    text,
    created_at  timestamptz NOT NULL DEFAULT now(),
    updated_at  timestamptz NOT NULL DEFAULT now(),
    deleted_at  timestamptz
);

-- ── Seed data ────────────────────────────────────────────────────────────────
-- All IDs are generated by gen_random_uuid(). CTEs chain via RETURNING so
-- each table can reference the freshly-generated IDs of the table above it.
WITH
  ins_country AS (
    INSERT INTO country (name, code) VALUES
      ('United States', 'US'),
      ('Ukraine',       'UA'),
      ('Germany',       'DE')
    RETURNING id, code
  ),
  ins_company AS (
    INSERT INTO company (name, industry, country_id)
    SELECT v.name, v.industry, c.id
    FROM (VALUES
      ('Acme Corp',    'Technology', 'US'),
      ('Nova Systems', 'Consulting', 'UA'),
      ('Berlin Labs',  'Research',   'DE')
    ) AS v(name, industry, code)
    JOIN ins_country c ON c.code = v.code
    RETURNING id, name
  ),
  ins_employer AS (
    INSERT INTO employer (name, company_id, location)
    SELECT v.name, c.id, v.location
    FROM (VALUES
      ('Acme Engineering', 'Acme Corp',    'San Francisco, CA'),
      ('Nova Kyiv Office', 'Nova Systems', 'Kyiv, Ukraine'),
      ('Berlin Labs HQ',   'Berlin Labs',  'Berlin, Germany')
    ) AS v(name, company_name, location)
    JOIN ins_company c ON c.name = v.company_name
    RETURNING id, name
  )
INSERT INTO people (name, email, employer_id, location)
SELECT v.name, v.email, e.id, v.location
FROM (VALUES
  ('Alice Johnson', 'alice@example.com', 'Acme Engineering', 'San Francisco, CA'),
  ('Oleksandr S.',  'alex@example.com',  'Nova Kyiv Office', 'Kyiv, Ukraine'),
  ('Hans Müller',   'hans@example.com',  'Berlin Labs HQ',   'Berlin, Germany'),
  ('Sara Conner',   'sara@example.com',  NULL::text,         'Remote')
) AS v(name, email, employer_name, location)
LEFT JOIN ins_employer e ON e.name = v.employer_name;
